import { Card } from '../types/game';

export const ALL_CARDS: Card[] = [
  // --- COMMON ---
  {
    id: 'bouncy',
    name: 'Bouncy Bullets',
    description: 'Bullets bounce off walls!',
    rarity: 'common',
    apply: (stats) => ({ ...stats, bounceCount: stats.bounceCount + 2, isBouncy: true }),
  },
  {
    id: 'big-bullet',
    name: 'Big Bullets',
    description: 'Bigger bullets, more damage, slower attack speed.',
    rarity: 'common',
    apply: (stats) => ({ 
      ...stats, 
      projectileSize: stats.projectileSize * 1.5, 
      damage: stats.damage * 1.3,
      fireRate: stats.fireRate * 1.2
    }),
  },
  {
    id: 'fast-bullets',
    name: 'Quick Shot',
    description: 'Faster attack speed, less damage.',
    rarity: 'common',
    apply: (stats) => ({ 
      ...stats, 
      fireRate: stats.fireRate * 0.7,
      damage: stats.damage * 0.8
    }),
  },
  {
    id: 'double-jump',
    name: 'Jet Boots',
    description: 'Jump slightly higher.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, jumpForce: stats.jumpForce * 1.15 }),
  },
  {
    id: 'weightless',
    name: 'Moon Gravity',
    description: 'Low gravity for the player.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, gravityScale: 0.7, jumpForce: stats.jumpForce * 1.2 }),
  },
  {
    id: 'sturdy',
    name: 'Sturdy Frame',
    description: 'Small health boost, small speed reduction.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth + 20, movementSpeed: stats.movementSpeed * 0.9 }),
  },
  {
    id: 'lightweight',
    name: 'Lightweight',
    description: 'Small speed boost, small health reduction.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.1, maxHealth: stats.maxHealth - 10 }),
  },
  {
    id: 'poker',
    name: 'The Poker',
    description: 'Small damage boost.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, damage: stats.damage + 5 }),
  },
  {
    id: 'lead-shoes',
    name: 'Lead Shoes',
    description: 'Higher gravity, more stability.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, gravityScale: 1.4, jumpForce: stats.jumpForce * 1.1 }),
  },
  {
    id: 'extra-pocket',
    name: 'Extra Pocket',
    description: 'Slightly more ammo capacity (simulated via reload speed).',
    rarity: 'common',
    apply: (stats) => ({ ...stats, reloadSpeed: stats.reloadSpeed * 1.2 }),
  },
  {
    id: 'nimble',
    name: 'Nimble Fingers',
    description: 'Small fire rate boost.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, fireRate: stats.fireRate * 0.9 }),
  },

  // --- UNCOMMON ---
  {
    id: 'vampirism',
    name: 'Vampirism',
    description: 'Boost max health significantly.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth + 50 }),
  },
  {
    id: 'tank',
    name: 'Tank',
    description: 'High health, slow movement.',
    rarity: 'uncommon',
    apply: (stats) => ({ 
      ...stats, 
      maxHealth: stats.maxHealth * 1.8,
      movementSpeed: stats.movementSpeed * 0.7
    }),
  },
  {
    id: 'buckshot',
    name: 'Buckshot',
    description: 'Triple the bullets, more spread, less damage.',
    rarity: 'uncommon',
    apply: (stats) => ({ 
      ...stats, 
      projectileCount: stats.projectileCount + 2,
      damage: stats.damage * 0.6,
      fireRate: stats.fireRate * 1.3
    }),
  },
  {
    id: 'bouncy-extra',
    name: 'Super Bounce',
    description: 'Bullets bounce 5 times!',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, bounceCount: stats.bounceCount + 5, isBouncy: true }),
  },
  {
    id: 'sprinter',
    name: 'Sprinter',
    description: 'Massive movement speed boost.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.5 }),
  },
  {
    id: 'rapid-fire',
    name: 'Overclock',
    description: 'Insane fire rate, tiny bullets.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, fireRate: stats.fireRate * 0.4, projectileSize: stats.projectileSize * 0.6, damage: stats.damage * 0.7 }),
  },
  {
    id: 'heavy-hitter',
    name: 'Heavy Hitter',
    description: 'High damage, high recoil (recoil is simulated by slow fire rate).',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, damage: stats.damage * 2, fireRate: stats.fireRate * 2.5 }),
  },
  {
    id: 'ricochet',
    name: 'Ricochet',
    description: 'Bullets bounce even more!',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, bounceCount: stats.bounceCount + 3, damage: stats.damage * 0.9 }),
  },
  {
    id: 'meditation',
    name: 'Meditation',
    description: 'Regenerate health slowly (simulated with max health buff).',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth + 30, movementSpeed: stats.movementSpeed * 0.95 }),
  },
  {
    id: 'steady-aim',
    name: 'Steady Aim',
    description: 'Faster projectiles, less spread.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, damage: stats.damage + 10, fireRate: stats.fireRate * 1.1 }),
  },

  // --- RARE ---
  {
    id: 'glass-cannon',
    name: 'Glass Cannon',
    description: 'Massive damage, but very low health.',
    rarity: 'rare',
    apply: (stats) => ({ 
      ...stats, 
      damage: stats.damage * 3,
      maxHealth: 30
    }),
  },
  {
    id: 'explosive',
    name: 'Explosive Bullets',
    description: 'Bullets explode on impact!',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, isExplosive: true, damage: stats.damage * 1.2 }),
  },
  {
    id: 'sniper',
    name: 'Sniper Shot',
    description: 'One massive, ultra-fast bullet.',
    rarity: 'rare',
    apply: (stats) => ({ 
      ...stats, 
      projectileSize: stats.projectileSize * 2,
      damage: stats.damage * 3,
      fireRate: stats.fireRate * 2.5,
      projectileCount: 1
    }),
  },
  {
    id: 'titan',
    name: 'Titan',
    description: 'Massive size, massive health, very slow.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth * 3, movementSpeed: stats.movementSpeed * 0.5, projectileSize: stats.projectileSize * 1.5 }),
  },
  {
    id: 'multi-shot',
    name: 'Volley',
    description: 'Fire a wall of 5 bullets.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, projectileCount: stats.projectileCount + 4, damage: stats.damage * 0.5, fireRate: stats.fireRate * 1.5 }),
  },
  {
    id: 'juggernaut',
    name: 'Juggernaut',
    description: 'High health and damage, but can barely jump.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth * 2, damage: stats.damage * 1.5, jumpForce: stats.jumpForce * 0.5 }),
  },
  {
    id: 'vampire-fangs',
    name: 'Vampire Fangs',
    description: 'Heal on dealing damage.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth + 40, damage: stats.damage * 0.8 }),
  },
  {
    id: 'teleport-jump',
    name: 'Blink',
    description: 'Massive jump force, low gravity.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, jumpForce: stats.jumpForce * 2, gravityScale: 0.5 }),
  },
  {
    id: 'berserker',
    name: 'Berserker',
    description: 'The lower your health, the more damage (simulated).',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, damage: stats.damage * 2.5, maxHealth: stats.maxHealth * 0.6 }),
  },

  // --- EPIC ---
  {
    id: 'homing',
    name: 'Seeker',
    description: 'Bullets track enemies! (Heat Seeking)',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, isHeatSeeking: true }),
  },
  {
    id: 'piercing',
    name: 'Drill Bit',
    description: 'Bullets pass through walls and enemies!',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, piercing: true }),
  },
  {
    id: 'atomic',
    name: 'Atomic Core',
    description: 'Huge explosions on hit.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, isExplosive: true, damage: stats.damage * 2 }),
  },
  {
    id: 'vortex',
    name: 'Vortex',
    description: 'Bullets pull enemies in.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.2, fireRate: stats.fireRate * 0.8 }),
  },
  {
    id: 'shadow',
    name: 'Shadow Walk',
    description: 'Faster movement and lower gravity.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.8, gravityScale: 0.4 }),
  },
  {
    id: 'elemental-burst',
    name: 'Elemental Burst',
    description: 'Random elemental effects (simulated).',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.5, fireRate: stats.fireRate * 0.8, bounceCount: stats.bounceCount + 2 }),
  },
  {
    id: 'nanobots',
    name: 'Nanobots',
    description: 'High health pool and fast fire rate.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth * 1.5, fireRate: stats.fireRate * 0.6 }),
  },
  {
    id: 'overload',
    name: 'System Overload',
    description: 'Fires massive amounts of bullets, but movement is restricted.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, projectileCount: stats.projectileCount + 5, movementSpeed: stats.movementSpeed * 0.4 }),
  },

  // --- LEGENDARY ---
  {
    id: 'god-complex',
    name: 'God Complex',
    description: 'Double everything. Double damage, double speed, double jump.',
    rarity: 'legendary',
    apply: (stats) => ({ 
      ...stats, 
      damage: stats.damage * 2, 
      movementSpeed: stats.movementSpeed * 2,
      jumpForce: stats.jumpForce * 1.5
    }),
  },
  {
    id: 'barrage',
    name: 'Meteor Shower',
    description: '10 bullets per shot. Pure chaos.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, projectileCount: stats.projectileCount + 9, fireRate: stats.fireRate * 1.2, damage: stats.damage * 0.4 }),
  },
  {
    id: 'immortal',
    name: 'Immortal',
    description: 'Restore 50% health and double max health.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth * 3 }),
  },
  {
    id: 'dragon-spirit',
    name: 'Dragon Spirit',
    description: 'Fire breath and massive damage.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, damage: stats.damage * 4, isExplosive: true }),
  },
  {
    id: 'warp-drive',
    name: 'Warp Drive',
    description: 'Near-instant movement and low gravity.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 3, gravityScale: 0.2 }),
  },
  {
    id: 'arsenal',
    name: 'Master Arsenal',
    description: 'Infinite ammo (simulated) and high damage.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, damage: stats.damage * 2.5, fireRate: stats.fireRate * 0.5, reloadSpeed: 10 }),
  },

  // --- MYTHICAL ---
  {
    id: 'reality-bend',
    name: 'Reality Bender',
    description: 'You are speed. You are death. You are the game.',
    rarity: 'mythical',
    apply: (stats) => ({ 
      ...stats, 
      damage: 999, 
      fireRate: 50, 
      movementSpeed: stats.movementSpeed * 3,
      jumpForce: stats.jumpForce * 2
    }),
  },
  {
    id: 'omega',
    name: 'Omega Protocol',
    description: 'Maximum health, maximum damage, maximum everything.',
    rarity: 'mythical',
    apply: (stats) => ({ 
      ...stats, 
      maxHealth: 1000, 
      damage: 100, 
      projectileCount: 5,
      fireRate: 100,
      movementSpeed: 10
    }),
  },
  {
    id: 'singularity',
    name: 'Singularity',
    description: 'The end of all things.',
    rarity: 'mythical',
    apply: (stats) => ({ 
      ...stats, 
      damage: 5000, 
      projectileCount: 1, 
      projectileSize: 5,
      isExplosive: true,
      fireRate: 1000
    }),
  },
  {
    id: 'ascended',
    name: 'Ascended',
    description: 'Transcend the limits of mortality.',
    rarity: 'mythical',
    apply: (stats) => ({ 
      ...stats, 
      maxHealth: 2000, 
      movementSpeed: 15, 
      jumpForce: 25,
      fireRate: 30,
      damage: 50
    }),
  },
  {
    id: 'chronos',
    name: 'Chronos',
    description: 'Time bends to your will. Bullets are extremely fast.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, projectileSpeed: 100, fireRate: 20 }),
  },
  {
    id: 'nebula',
    name: 'Nebula',
    description: 'A cloud of chaotic energy. Massive spread of small, fast projectiles.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, projectileCount: 20, damage: 15, projectileSize: 0.4, projectileSpeed: 40 }),
  },
  {
    id: 'gravity-master',
    name: 'Gravity Master',
    description: 'Control the very weight of the world.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, gravityScale: 0.1, jumpForce: 30, movementSpeed: 20 }),
  },

  // --- ADDED EXTRA CARDS ---
  {
    id: 'heavy-bullets',
    name: 'Heavy Bullets',
    description: 'High damage, but they fall faster (simulated).',
    rarity: 'common',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.5, projectileSpeed: stats.projectileSpeed * 0.8 }),
  },
  {
    id: 'small-target',
    name: 'Small Target',
    description: 'Harder to hit! (Simulated via slightly higher speed).',
    rarity: 'common',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.15 }),
  },
  {
    id: 'poison-darts',
    name: 'Poison Darts',
    description: 'Deals damage over time (simulated via base damage buff).',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, damage: stats.damage + 15 }),
  },
  {
    id: 'wind-walker',
    name: 'Wind Walker',
    description: 'Move like the breeze.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.3, jumpForce: stats.jumpForce * 1.1 }),
  },
  {
    id: 'plasma-core',
    name: 'Plasma Core',
    description: 'Hotter bullets, more impact.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.6, projectileSize: stats.projectileSize * 1.4 }),
  },
  {
    id: 'chain-reaction',
    name: 'Chain Reaction',
    description: 'Explosions lead to more chaos.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, isExplosive: true, projectileCount: stats.projectileCount + 1 }),
  },
  {
    id: 'stealth-suit',
    name: 'Stealth Suit',
    description: 'Invisibility is key! (Simulated via massive speed and low gravity).',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 2, gravityScale: 0.3 }),
  },
  {
    id: 'orbital-strike',
    name: 'Orbital Strike',
    description: 'Death from above.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, damage: stats.damage * 3, isExplosive: true, fireRate: stats.fireRate * 1.5 }),
  },
  {
    id: 'void-walker',
    name: 'Void Walker',
    description: 'Phase through existence.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth * 4, movementSpeed: stats.movementSpeed * 0.5 }),
  },
  {
    id: 'supernova',
    name: 'Supernova',
    description: 'The brightest explosion.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, damage: stats.damage * 5, isExplosive: true, projectileSize: 10 }),
  },
  // --- 30 NEW CARDS ---
  {
    id: 'gravity-well-card',
    name: 'Gravity Well',
    description: 'Projectiles pull players in.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, isBlackHole: true }),
  },
  {
    id: 'shatter',
    name: 'Shatter',
    description: 'Projectiles split on impact.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, damage: stats.damage * 0.7, projectileCount: stats.projectileCount * 2 }),
  },
  {
    id: 'laser-focus',
    name: 'Laser Focus',
    description: 'Extremely fast, thin projectiles.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, projectileSpeed: stats.projectileSpeed * 2.5, projectileSize: stats.projectileSize * 0.3, damage: stats.damage * 1.4 }),
  },
  {
    id: 'jungle-soul',
    name: 'Jungle Soul',
    description: 'Higher jump, faster reload.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, jumpForce: stats.jumpForce * 1.3, reloadSpeed: stats.reloadSpeed * 1.5 }),
  },
  {
    id: 'lava-blood',
    name: 'Lava Blood',
    description: 'Explosive resistance, more damage.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.8, maxHealth: stats.maxHealth + 20 }),
  },
  {
    id: 'frost-bite',
    name: 'Frost Bite',
    description: 'Slows enemies on hit.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, damage: stats.damage + 5 }),
  },
  {
    id: 'wind-blade-card',
    name: 'Wind Blade',
    description: 'Fast slices, high movement speed.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.6, fireRate: stats.fireRate * 0.7 }),
  },
  {
    id: 'orbital-laser',
    name: 'Orbital Laser',
    description: 'Devastating overhead strike.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, damage: stats.damage * 4, isExplosive: true, fireRate: stats.fireRate * 2 }),
  },
  {
    id: 'micro-bot',
    name: 'Micro-Bots',
    description: 'Fast movement, tiny hitbox.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.4, projectileSize: stats.projectileSize * 0.8 }),
  },
  {
    id: 'titanium-plate',
    name: 'Titanium Plate',
    description: 'Immense health, low jump.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth + 150, jumpForce: stats.jumpForce * 0.6 }),
  },
  {
    id: 'gamma-ray',
    name: 'Gamma Ray',
    description: 'Piercing green lasers.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, piercing: true, damage: stats.damage * 2, fireRate: stats.fireRate * 0.5 }),
  },
  {
    id: 'echo-chamber',
    name: 'Echo Chamber',
    description: 'Massive bounce count.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, bounceCount: stats.bounceCount + 10, isBouncy: true }),
  },
  {
    id: 'void-step',
    name: 'Void Step',
    description: 'Teleportation jumps.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, jumpForce: stats.jumpForce * 3, gravityScale: 0.1 }),
  },
  {
    id: 'blaze-trail',
    name: 'Blaze Trail',
    description: 'Speed leaves fire.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.4, isExplosive: true }),
  },
  {
    id: 'hyper-reload',
    name: 'Hyper Reload',
    description: 'Infinite ammo feel.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, reloadSpeed: stats.reloadSpeed * 5, fireRate: stats.fireRate * 0.8 }),
  },
  {
    id: 'chaos-theory',
    name: 'Chaos Theory',
    description: 'Randomized fire pattern.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, projectileCount: stats.projectileCount + 3, damage: stats.damage * 1.2 }),
  },
  {
    id: 'diamond-skin',
    name: 'Diamond Skin',
    description: 'Massive health pool.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth * 2.5 }),
  },
  {
    id: 'soul-stealer',
    name: 'Soul Stealer',
    description: 'Heal on every hit.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.5, maxHealth: stats.maxHealth + 100 }),
  },
  {
    id: 'phantom-limb',
    name: 'Phantom Limb',
    description: 'Near-invisible movement.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 2, gravityScale: 0.2 }),
  },
  {
    id: 'core-meltdown',
    name: 'Core Meltdown',
    description: 'Every shot is a nuke.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, isExplosive: true, damage: stats.damage * 4, fireRate: stats.fireRate * 3 }),
  },
  {
    id: 'mirage',
    name: 'Mirage',
    description: 'Multiple projectiles from shadows.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, projectileCount: stats.projectileCount + 4, damage: stats.damage * 0.4 }),
  },
  {
    id: 'super-slick',
    name: 'Super Slick',
    description: 'High friction traversal.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.4 }),
  },
  {
    id: 'boulder-dash',
    name: 'Boulder Dash',
    description: 'Heavy and fast.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, gravityScale: 2.0, movementSpeed: stats.movementSpeed * 1.5 }),
  },
  {
    id: 'static-cling',
    name: 'Static Cling',
    description: 'Stick to walls (simulated speed).',
    rarity: 'common',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.2, jumpForce: stats.jumpForce * 1.2 }),
  },
  {
    id: 'dark-matter',
    name: 'Dark Matter',
    description: 'Slow bullets, extreme damage.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, projectileSpeed: stats.projectileSpeed * 0.4, damage: stats.damage * 3 }),
  },
  {
    id: 'light-speed',
    name: 'Light Speed',
    description: 'Instant travel projectiles.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, projectileSpeed: stats.projectileSpeed * 10, fireRate: stats.fireRate * 0.7 }),
  },
  {
    id: 'plasma-shield-card',
    name: 'Plasma Shield',
    description: 'Brief invincibility boost.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, shieldDuration: stats.shieldDuration + 2000, maxHealth: stats.maxHealth + 50 }),
  },
  {
    id: 'over-9000',
    name: 'Over 9000',
    description: 'Power beyond belief.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, damage: stats.damage * 10, fireRate: stats.fireRate * 2, movementSpeed: stats.movementSpeed * 2 }),
  },
  {
    id: 'alpha-strike',
    name: 'Alpha Strike',
    description: 'First shot deals double damage.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.1 }),
  },
  {
    id: 'omega-beam',
    name: 'Omega Beam',
    description: 'Finality.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, damage: 9999, fireRate: 2000, projectileSize: 10 })
  },
  // --- 50 NEW CRAFTED CARDS ---
  {
    id: 'blood-pact',
    name: 'Blood Pact',
    description: '25% Lifesteal, but 20% less max health.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, lifesteal: stats.lifesteal + 0.25, maxHealth: stats.maxHealth * 0.8 }),
  },
  {
    id: 'thorns-aura',
    name: 'Thorns Aura',
    description: 'Reflect 5 damage back to attackers.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, thorns: stats.thorns + 5 }),
  },
  {
    id: 'toxic-venom',
    name: 'Toxic Venom',
    description: '30% chance to poison enemies on hit.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, poisonChance: stats.poisonChance + 0.3 }),
  },
  {
    id: 'inferno-touch',
    name: 'Inferno Touch',
    description: '20% chance to burn enemies on hit.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, burnChance: stats.burnChance + 0.2 }),
  },
  {
    id: 'iron-skin',
    name: 'Iron Skin',
    description: '+5 Armor (flat damage reduction).',
    rarity: 'common',
    apply: (stats) => ({ ...stats, armor: stats.armor + 5 }),
  },
  {
    id: 'ghost-form',
    name: 'Ghost Form',
    description: '15% chance to dodge any damage.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, dodgeChance: stats.dodgeChance + 0.15 }),
  },
  {
    id: 'necromancer',
    name: 'Necromancer',
    description: '20% chance to summon a minion sentry on kill.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, necroChance: stats.necroChance + 0.2 }),
  },
  {
    id: 'triple-jump-card',
    name: 'Sky Dancer',
    description: '+1 Extra Jump.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, extraJumps: stats.extraJumps + 1 }),
  },
  {
    id: 'life-link',
    name: 'Life Link',
    description: 'Shared health pool with your damage (10% Lifesteal).',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, lifesteal: stats.lifesteal + 0.1 }),
  },
  {
    id: 'vampire-lord',
    name: 'Vampire Lord',
    description: '50% Lifesteal, massive health, slow fire rate.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, lifesteal: stats.lifesteal + 0.5, maxHealth: stats.maxHealth * 1.5, fireRate: stats.fireRate * 1.5 }),
  },
  {
    id: 'spiky-armor',
    name: 'Spiky Armor',
    description: 'Armor +10, Thorns +10.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, armor: stats.armor + 10, thorns: stats.thorns + 10 }),
  },
  {
    id: 'blur',
    name: 'Blur',
    description: '30% dodge chance, but lower health.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, dodgeChance: stats.dodgeChance + 0.3, maxHealth: stats.maxHealth * 0.7 }),
  },
  {
    id: 'plague-bearer',
    name: 'Plague Bearer',
    description: 'Poison chance 100%, but your damage is halved.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, poisonChance: 1.0, damage: stats.damage * 0.5 }),
  },
  {
    id: 'pyromaniac',
    name: 'Pyromaniac',
    description: 'Burn chance 100%, explosions everywhere.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, burnChance: 1.0, isExplosive: true }),
  },
  {
    id: 'lich-king',
    name: 'Lich King',
    description: 'Sentry kills spawn more sentries (Necro +50%).',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, necroChance: stats.necroChance + 0.5, maxHealth: stats.maxHealth * 2 }),
  },
  {
    id: 'cloud-stepper',
    name: 'Cloud Stepper',
    description: '+2 Extra Jumps.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, extraJumps: stats.extraJumps + 2, gravityScale: 0.6 }),
  },
  {
    id: 'reinforced-plating',
    name: 'Reinforced Plating',
    description: '+20 Armor, slow movement.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, armor: stats.armor + 20, movementSpeed: stats.movementSpeed * 0.7 }),
  },
  {
    id: 'berserker-rage',
    name: 'Berserker Rage',
    description: 'Damage +100%, Armor -10.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, damage: stats.damage * 2, armor: stats.armor - 10 }),
  },
  {
    id: 'voodoo-doll',
    name: 'Voodoo Doll',
    description: 'Damage dealt reflects 50% back as Thorns.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, thorns: stats.thorns + 20 }),
  },
  {
    id: 'toxic-mist',
    name: 'Toxic Mist',
    description: 'Small damage projectiles, high poison.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, damage: stats.damage * 0.5, poisonChance: stats.poisonChance + 0.5 }),
  },
  {
    id: 'phoenix-legacy',
    name: 'Phoenix Legacy',
    description: 'Immense burn chance, revive potential (HP boost).',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, burnChance: 1.0, maxHealth: stats.maxHealth + 200 }),
  },
  {
    id: 'nanoshield',
    name: 'Nano-Shield',
    description: 'Flat damage reduction +15.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, armor: stats.armor + 15 }),
  },
  {
    id: 'unfazed',
    name: 'Unfazed',
    description: 'Immune to slow (simulated via speed boost).',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.2, armor: stats.armor + 2 }),
  },
  {
    id: 'blood-thirst',
    name: 'Blood Thirst',
    description: 'Killing heals you to full (Lifesteal +100%).',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, lifesteal: 1.0 }),
  },
  {
    id: 'soul-guard',
    name: 'Soul Guard',
    description: 'Necro summons protect you.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, necroChance: stats.necroChance + 0.3, armor: stats.armor + 5 }),
  },
  {
    id: 'wraith-wings',
    name: 'Wraith Wings',
    description: 'Fly! (Low gravity, high extra jumps).',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, gravityScale: 0.2, extraJumps: stats.extraJumps + 5 }),
  },
  {
    id: 'obsidian-skin',
    name: 'Obsidian Skin',
    description: 'Immune to burn (Flat armor +30).',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, armor: stats.armor + 30, burnChance: 0 }),
  },
  {
    id: 'lucky-clover',
    name: 'Lucky Clover',
    description: 'Dodge chance +10%, Damage +10%.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, dodgeChance: stats.dodgeChance + 0.1, damage: stats.damage * 1.1 }),
  },
  {
    id: 'dead-man-switch',
    name: 'Dead Man Switch',
    description: 'Explode on death (simulated via necro + high bomb ammo).',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, necroChance: 1.0, isExplosive: true }),
  },
  {
    id: 'viper-strike',
    name: 'Viper Strike',
    description: 'Poison +50%, attack speed +50%.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, poisonChance: stats.poisonChance + 0.5, fireRate: stats.fireRate * 0.5 }),
  },
  {
    id: 'dragon-scales',
    name: 'Dragon Scales',
    description: 'Armor +20, Thorns +5.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, armor: stats.armor + 20, thorns: stats.thorns + 5 }),
  },
  {
    id: 'shadow-dancer',
    name: 'Shadow Dancer',
    description: 'Dodge +40%, speed +40%.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, dodgeChance: stats.dodgeChance + 0.4, movementSpeed: stats.movementSpeed * 1.4 }),
  },
  {
    id: 'grim-scythe-card',
    name: 'Grim Scythe',
    description: 'Necro summons deal more damage.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, necroChance: stats.necroChance + 0.4, damage: stats.damage * 1.2 }),
  },
  {
    id: 'energy-barrier',
    name: 'Energy Barrier',
    description: 'Shield duration +5s.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, shieldDuration: stats.shieldDuration + 5000 }),
  },
  {
    id: 'seraphim-grace',
    name: 'Seraphim',
    description: 'Flight and massive health regen (simulated).',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, gravityScale: 0.3, maxHealth: stats.maxHealth * 5, extraJumps: stats.extraJumps + 3 }),
  },
  {
    id: 'tank-buster',
    name: 'Tank Buster',
    description: 'Ignore armor, massive damage.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, damage: stats.damage * 2.5, armor: 0 }),
  },
  {
    id: 'acid-reflux',
    name: 'Acid Reflux',
    description: 'Poison chance based on hits (100% poison).',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, poisonChance: 1.0 }),
  },
  {
    id: 'hyper-activity',
    name: 'Hyper Activity',
    description: 'Fire rate x4, damage /4.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, fireRate: stats.fireRate * 0.25, damage: stats.damage * 0.25 }),
  },
  {
    id: 'soul-drain',
    name: 'Soul Drain',
    description: 'Lifesteal +20%, Poison +20%.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, lifesteal: stats.lifesteal + 0.2, poisonChance: stats.poisonChance + 0.2 }),
  },
  {
    id: 'juggernaut-plating',
    name: 'Juggernaut Plating',
    description: 'Armor +50, can barely move.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, armor: stats.armor + 50, movementSpeed: stats.movementSpeed * 0.3 }),
  },
  {
    id: 'ninja-arts',
    name: 'Ninja Arts',
    description: 'Extra jump +3, Dodge +20%.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, extraJumps: stats.extraJumps + 3, dodgeChance: stats.dodgeChance + 0.2 }),
  },
  {
    id: 'blood-god',
    name: 'Blood God',
    description: 'Lifesteal 100%, Health +500, Damage +500.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, lifesteal: 1.0, maxHealth: stats.maxHealth + 500, damage: stats.damage + 500 }),
  },
  {
    id: 'void-pulse',
    name: 'Void Pulse',
    description: 'Gravity grenade on every shot (simulated).',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, isExplosive: true, damage: stats.damage * 1.5 }),
  },
  {
    id: 'cybernetic-aug',
    name: 'Augmented',
    description: 'All stats slightly boosted.',
    rarity: 'common',
    apply: (stats) => ({ 
        ...stats, 
        maxHealth: stats.maxHealth + 10, 
        damage: stats.damage + 5, 
        movementSpeed: stats.movementSpeed + 1, 
        armor: stats.armor + 2 
    }),
  },
  {
    id: 'haunted-armor',
    name: 'Haunted Armor',
    description: 'Armor +20, Necro +20%.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, armor: stats.armor + 20, necroChance: stats.necroChance + 0.2 }),
  },
  {
    id: 'storm-chaser',
    name: 'Storm Chaser',
    description: 'Speed +100%, Bouncy bullets.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 2, isBouncy: true, bounceCount: stats.bounceCount + 5 }),
  },
  {
    id: 'sun-blessing',
    name: 'Sun Blessing',
    description: 'Burn chance +50%, damage +50%.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, burnChance: stats.burnChance + 0.5, damage: stats.damage * 1.5 }),
  },
  {
    id: 'moon-blessing',
    name: 'Moon Blessing',
    description: 'Gravity scale -50%, dodge +20%.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, gravityScale: stats.gravityScale * 0.5, dodgeChance: stats.dodgeChance + 0.2 }),
  },
  {
    id: 'recursive-loop',
    name: 'Recursive',
    description: 'Triple projectile count, half damage.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, projectileCount: stats.projectileCount * 3, damage: stats.damage * 0.5 }),
  },
  {
    id: 'ultimate-survivor',
    name: 'Survivor',
    description: 'Armor +10, Dodge +10%, Lifesteal +10%.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, armor: stats.armor + 10, dodgeChance: stats.dodgeChance + 0.1, lifesteal: stats.lifesteal + 0.1 }),
  },
  {
    id: 'newtons-nightmare',
    name: "Newton's Nightmare",
    description: 'Projectiles pull enemies toward them.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, projectileGravity: stats.projectileGravity + 0.8 }),
  },
  {
    id: 'recoil-propulsion',
    name: 'Recoil Propulsion',
    description: '300% Recoil, but no contact damage while airborne.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, recoilPropulsion: stats.recoilPropulsion + 3.0, noAirContactDamage: true }),
  },
  {
    id: 'sticky-friction',
    name: 'Sticky Friction',
    description: 'Walk on walls/ceilings. Hits stick enemies to the ground.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, wallWalk: true, movementSpeed: stats.movementSpeed * 0.8 }),
  },
  {
    id: 'echo-strikes',
    name: 'Echo Strikes',
    description: 'Actions are repeated by a ghost 0.5s later.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, echoStrikes: true, fireRate: stats.fireRate * 1.5 }),
  },
  {
    id: 'kinetic-battery',
    name: 'Kinetic Battery',
    description: 'Absorb knockback to power up your next attack.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, kineticBattery: true, armor: stats.armor + 5 }),
  },
  // --- SOCKET CARDS ---
  {
    id: 'heavy-treads',
    name: 'Heavy Treads',
    description: '[CORE] Immune to knockback but 20% slower.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, coreSlot: 'heavy-treads', movementSpeed: stats.movementSpeed * 0.8, armor: stats.armor + 10 }),
  },
  {
    id: 'jet-heels',
    name: 'Jet-Heels',
    description: '[CORE] Infinite jumps but high friction ground movement.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, coreSlot: 'jet-heels', extraJumps: 99, movementSpeed: stats.movementSpeed * 0.7 }),
  },
  {
    id: 'repulsion-field',
    name: 'Repulsion Field',
    description: '[UTILITY] Aura pushes away nearby loose projectiles.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, utilitySlot: 'repulsion-field', neonGlow: true }),
  },
  {
    id: 'scavenger',
    name: 'Scavenger',
    description: '[UTILITY] Pulls weapons toward you automatically.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, utilitySlot: 'scavenger', movementSpeed: stats.movementSpeed * 1.1 }),
  },
  {
    id: 'neon-blur',
    name: 'Neon Blur',
    description: '[VISUAL] High speed leaves a neon motion blur.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, trailEffect: true, movementSpeed: stats.movementSpeed * 1.1 }),
  },
  {
    id: 'juggernaut-frame',
    name: 'Juggernaut Frame',
    description: '[VISUAL] Thicker, bolder outline. HP +50.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, neonGlow: true, maxHealth: stats.maxHealth + 50 }),
  },
  // --- MATCH MODIFIERS ---
  {
    id: 'entropy-mode',
    name: 'Entropy Mode',
    description: '[MATCH] Every 10s, all unequipped weapons on floor explode. High Rarity.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, entropyMode: true }),
  },
  {
    id: 'bullet-time-parry',
    name: 'Bullet Time Parries',
    description: '[MATCH] Time slows down for 1.5s when bullets collide.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, bulletTimeParry: true }),
  },
  {
    id: 'quantum-swap',
    name: 'Quantum Swap',
    description: '[SELF] Become a Ghost after death with 1 Pulse-Push charge.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, quantumSwap: true }),
  },
  {
    id: 'final-stand-viz',
    name: 'Last Stand Protocol',
    description: '[VISUAL] Low health triggers desaturation and glitch effects. +20% damage when low.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, finalStandVisuals: true, damage: stats.damage * 1.2 }),
  },
  {
    id: 'debris-field',
    name: 'Debris Field',
    description: '[MATCH] Match spawns with significantly more chairs, crates, and debris.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, extraDebris: true }),
  },
  // --- ELEMENTAL MASTERY ---
  {
    id: 'frost-nova',
    name: 'Frost Nova',
    description: 'Enemies near your projectiles are slowed significantly.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, fireRate: stats.fireRate * 0.9, damage: stats.damage + 10 }),
  },
  {
    id: 'static-link',
    name: 'Static Link',
    description: 'Damage chains between nearby enemies (simulated).',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.3, projectileCount: stats.projectileCount + 1 }),
  },
  {
    id: 'vile-toxin',
    name: 'Vile Toxin',
    description: 'Poison damage lasts twice as long.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, poisonChance: stats.poisonChance + 0.4 }),
  },
  {
    id: 'solar-flare',
    name: 'Solar Flare',
    description: 'Huge projectiles, extreme burn chance.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, projectileSize: stats.projectileSize * 1.8, burnChance: stats.burnChance + 0.6 }),
  },
  {
    id: 'tempest-wing',
    name: 'Tempest Wing',
    description: 'Jump higher for every kill this round (simulated).',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, jumpForce: stats.jumpForce * 1.5 }),
  },
  // --- ARCHETYPE SPECIALIZATION ---
  {
    id: 'titan-core',
    name: 'Titan Core',
    description: 'Titan archetype: Armor +30, Speed -10%. Others: Gravity +20%.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, armor: stats.armor + 15, stability: (stats.stability || 100) + 50 }),
  },
  {
    id: 'wraith-soul',
    name: 'Wraith Soul',
    description: 'Wraith archetype: Dodge +20%. Others: Speed +10%.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, dodgeChance: stats.dodgeChance + 0.15, movementSpeed: stats.movementSpeed * 1.2 }),
  },
  {
    id: 'acrobat-skill',
    name: 'Master Acrobat',
    description: 'Acrobat archetype: Extra Jumps +2. Others: Jump force +20%.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, extraJumps: stats.extraJumps + 2 }),
  },
  {
    id: 'gunner-sight',
    name: 'Gunner Sight',
    description: 'Gunner archetype: Fire rate +30%. Others: Damage +10%.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, fireRate: stats.fireRate * 0.7, damage: stats.damage * 1.1 }),
  },
  // --- PHYSICS & UTILITY ---
  {
    id: 'anti-grav-unit',
    name: 'Anti-Grav Unit',
    description: 'Gravity -80%, Movement Speed +50%.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, gravityScale: 0.2, movementSpeed: stats.movementSpeed * 1.5 }),
  },
  {
    id: 'massive-slugs',
    name: 'Massive Slugs',
    description: 'Projectiles are huge, slow, and deal 400% damage.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, projectileSize: 5, projectileSpeed: 5, damage: stats.damage * 4 }),
  },
  {
    id: 'needle-bullets',
    name: 'Needle Bullets',
    description: 'Bullets are tiny and fast, ignore armor.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, projectileSize: 0.2, projectileSpeed: 60, armor: 0, damage: stats.damage * 0.8 }),
  },
  {
    id: 'magnetic-tether',
    name: 'Magnetic Tether',
    description: 'Bullets pull guns toward you (simulated).',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, utilitySlot: 'scavenger' }),
  },
  {
    id: 'repulsion-armor',
    name: 'Repulsion Armor',
    description: 'Enemies that touch you are pushed back hard.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, thorns: stats.thorns + 2, stability: (stats.stability || 100) + 100 }),
  },
  // --- WILD & CHAOTIC ---
  {
    id: 'mirror-dimension',
    name: 'Mirror Dimension',
    description: 'Projectiles bounce 20 times.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, isBouncy: true, bounceCount: stats.bounceCount + 20 }),
  },
  {
    id: 'shrapnel-burst',
    name: 'Shrapnel',
    description: 'Explosions release smaller projectiles (simulated).',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, isExplosive: true, damage: stats.damage * 1.2 }),
  },
  {
    id: 'vampiric-aura',
    name: 'Vampiric Aura',
    description: 'Drains health from nearby enemies automatically (simulated).',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, lifesteal: stats.lifesteal + 0.3, maxHealth: stats.maxHealth + 100 }),
  },
  {
    id: 'chronos-touch',
    name: 'Chronos Touch',
    description: 'Small chance to freeze on hit (10%).',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, fireRate: stats.fireRate * 0.9 }),
  },
  {
    id: 'overdrive-relay',
    name: 'Overdrive',
    description: 'When health is below 30%, speed is doubled.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.2, damage: stats.damage * 1.2 }),
  },
  // --- 20 MORE MISC ---
  {
    id: 'lead-plating',
    name: 'Lead Plating',
    description: 'Armor +40, but gravity +100%.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, armor: stats.armor + 40, gravityScale: stats.gravityScale * 2.0 }),
  },
  {
    id: 'phantom-rounds',
    name: 'Phantom Rounds',
    description: 'Bullets ignore walls but deal 30% less damage.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, piercing: true, damage: stats.damage * 0.7 }),
  },
  {
    id: 'rebound-master',
    name: 'Rebound Master',
    description: 'Damage increases for every bounce.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, isBouncy: true, bounceCount: stats.bounceCount + 3, damage: stats.damage * 1.1 }),
  },
  {
    id: 'growth-hormone',
    name: 'Growth Hormone',
    description: 'Character size +50%, Health +200, Speed -20%.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth + 200, movementSpeed: stats.movementSpeed * 0.8 }),
  },
  {
    id: 'shrink-serum',
    name: 'Shrink Serum',
    description: 'Character size -50%, Speed +30%, Health -50.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth - 50, movementSpeed: stats.movementSpeed * 1.3 }),
  },
  {
    id: 'gamma-burst-card',
    name: 'Gamma Burst',
    description: 'Explosions are massive and green.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, isExplosive: true, damage: stats.damage * 1.3 }),
  },
  {
    id: 'electro-net',
    name: 'Electro-Net',
    description: 'Bullets slow enemies by 50% for 1s.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, damage: stats.damage + 5 }),
  },
  {
    id: 'obsidian-edge',
    name: 'Obsidian Edge',
    description: 'Melee damage +200%.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.5 }),
  },
  {
    id: 'spectral-cloak',
    name: 'Spectral Cloak',
    description: 'Dodge chance +50% for the first 10s of a round.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, dodgeChance: stats.dodgeChance + 0.3 }),
  },
  {
    id: 'titan-fall',
    name: 'Titan Fall',
    description: 'Gravity +300%, Fall damage removed (simulated).',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, gravityScale: 4.0, maxHealth: stats.maxHealth + 100 }),
  },
  {
    id: 'wind-whisper',
    name: 'Wind Whisper',
    description: 'Extra jump +1, Speed +20%.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, extraJumps: stats.extraJumps + 1, movementSpeed: stats.movementSpeed * 1.2 }),
  },
  {
    id: 'life-bloom',
    name: 'Life Bloom',
    description: 'Regenerate 1 HP every second.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth + 50 }),
  },
  {
    id: 'deadly-aim',
    name: 'Deadly Aim',
    description: 'Crit chance +20% (simulated via damage).',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.25 }),
  },
  {
    id: 'quick-draw',
    name: 'Quick Draw',
    description: 'Switch weapons instantly, Reload +100%.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, reloadSpeed: stats.reloadSpeed * 2.0 }),
  },
  {
    id: 'shield-generator',
    name: 'Shield Gen',
    description: 'Armor +5, Shield duration +1s.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, armor: stats.armor + 5, shieldDuration: stats.shieldDuration + 1000 }),
  },
  {
    id: 'heavy-artillery',
    name: 'Heavy Artillery',
    description: 'Explosive bullets deal 2x damage, but fire rate is halved.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, isExplosive: true, damage: stats.damage * 2, fireRate: stats.fireRate * 2.0 }),
  },
  {
    id: 'lightweight-rounds',
    name: 'Feather Shots',
    description: 'Bullets don’t push enemies but travel extremely fast.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, projectileSpeed: stats.projectileSpeed * 2.0, damage: stats.damage * 0.9 }),
  },
  {
    id: 'dragon-fire',
    name: "Dragon's Fire",
    description: 'Massive burn chance, half ammo.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, burnChance: 0.8, damage: stats.damage * 1.5 }),
  },
  {
    id: 'void-energy',
    name: 'Void Energy',
    description: 'Piercing bullets deal damage over time.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, piercing: true, poisonChance: 0.3 }),
  },
  {
    id: 'master-blaster',
    name: 'Master Blaster',
    description: 'Every 5th shot is a nuke (simulated).',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, isExplosive: true, damage: stats.damage * 2.5, projectileCount: stats.projectileCount + 1 })
  },
  {
    id: 'void_siphon',
    name: 'Void Siphon',
    description: 'Absorbing projectiles restores 2 HP and grants 5% temporary damage.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth + 10, canAbsorbProjectiles: true }),
  },
  {
    id: 'momentum_engine',
    name: 'Momentum Engine',
    description: 'Gain 2% damage bonus for every 10 units of speed.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.1 }),
  },
  {
    id: 'tactical_patience',
    name: 'Tactical Patience',
    description: 'While standing still for 2s, gain a 40 HP recharging shield.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, armor: stats.armor + 5, stationaryShield: true }),
  },
  {
    id: 'berserk_fury',
    name: 'Berserk Fury',
    description: 'Damage increases by up to 50% as health decreases.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.2, lowHealthBerserk: true }),
  },
  {
    id: 'mirror_armor',
    name: 'Mirror Armor',
    description: 'Reflect 20% of taken damage back to the attacker.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, thorns: (stats.thorns || 0) + 20 }),
  },
  {
    id: 'event_horizon',
    name: 'Event Horizon',
    description: 'Projectiles have a 5% chance to spawn a tiny gravity well on impact.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, projectileGravity: (stats.projectileGravity || 0) + 1 }),
  },
  {
    id: 'starlight_blessing',
    name: 'Starlight Blessing',
    description: 'Projectiles have a slight glow and 50% more speed.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, projectileSpeed: stats.projectileSpeed * 1.5 }),
  },
  {
    id: 'echo_pulse',
    name: 'Echo Pulse',
    description: 'Your successful hits release a secondary sonic wave for 10 damage.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.1 }),
  },
  {
    id: 'chrono_trigger',
    name: 'Chrono Trigger',
    description: 'Killing an enemy briefly slows down time for everyone but you.',
    rarity: 'legendary',
    apply: (stats) => ({ ...stats, bulletTimeParry: true }),
  },
  {
    id: 'quantum_entanglement',
    name: 'Quantum Entanglement',
    description: 'When you take damage, there is a 10% chance to swap positions with the attacker.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, quantumSwap: true }),
  },
  {
    id: 'heavy_plating',
    name: 'Heavy Plating',
    description: 'Increases health by 50 but reduces movement speed by 15%.',
    rarity: 'common',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth + 50, movementSpeed: stats.movementSpeed * 0.85 }),
  },
  {
    id: 'glass_cannon',
    name: 'Glass Cannon',
    description: 'Reduces health by 40% but doubles damage.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth * 0.6, damage: stats.damage * 2.0 }),
  },
  {
    id: 'vampiric_bite',
    name: 'Vampiric Bite',
    description: 'Your melee attacks restore 10% of damage dealt as health.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, lifesteal: (stats.lifesteal || 0) + 0.1 }),
  },
  {
    id: 'storm_caller',
    name: 'Storm Caller',
    description: 'Your projectiles have a 10% chance to strike the target with lightning.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.1 }),
  },
  {
    id: 'frost_bite',
    name: 'Frost Bite',
    description: 'Chilled enemies take 15% more damage.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.05 }),
  },
  {
    id: 'plasma_infusion',
    name: 'Plasma Infusion',
    description: 'Projectiles deal burn damage over 3 seconds.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.1, burnChance: 0.3 }),
  },
  {
    id: 'kinetic_overflow',
    name: 'Kinetic Overflow',
    description: 'Collecting a weapon drop releases a kinetic blast around you.',
    rarity: 'epic',
    apply: (stats) => ({ ...stats, movementSpeed: stats.movementSpeed * 1.1 }),
  },
  {
    id: 'shadow_affinity',
    name: 'Shadow Affinity',
    description: 'While in shadows (or jungle grass), regenerate 2 HP per second.',
    rarity: 'rare',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth + 10, vinesRegen: true }),
  },
  {
    id: 'orbital_strike_beacon',
    name: 'Orbital Beacon',
    description: 'Every 15s, a massive orbital laser strikes the nearest opponent.',
    rarity: 'mythical',
    apply: (stats) => ({ ...stats, damage: stats.damage * 1.2 }),
  },
  {
    id: 'nano_repair_bots',
    name: 'Nano Repair',
    description: 'Slowly regenerates 1 HP every 2 seconds.',
    rarity: 'uncommon',
    apply: (stats) => ({ ...stats, maxHealth: stats.maxHealth + 20 }),
  }
];
